### PR TITLE
style: 💄 use import conductor to order imports

### PR DESCRIPTION
**Pull request by kreuzerk**
@shaharkazaz FYI

### CODE REVIEW

**Comment by shaharkazaz** [comment]
@kreuzerk I would run the import conductor before the prettier to make sure everything is aligned.

**Comment by kreuzerk** [comment]
@shaharkazaz Yes that would make sense - I tried that but unfortunately, the staged flag isn't yet working with the ignore flag.  I need to ensure that the comment in the `svg-to-ts` file in the `bin` folder isn't reordered. 

Means, if somebody would edit the `svg-to-ts.ts` file `import-conductor` would break it once the pre commit hook runs.

**Comment by shaharkazaz** [comment]
@kreuzerk I see. I would open an issue in the conductor for it and another issue here linked to it to change the order once supported there.

**Review by shaharkazaz — APPROVED** [review]

**Comment by shaharkazaz** [comment]
@kreuzerk the conductor `ignore` property seems to be working when running in staged mode.
image
So I'm not sure what's the issue you are referring to 🤔

**Comment by kreuzerk** [comment]
@shaharkazaz thx a lot for the reply. 🤔 Maybe I made a typo in the ignore path pattern. Will check again

**Comment by kreuzerk** [comment]
I added the following to my `husky` config.

```json
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged && import-conductor --staged -i './src/bin/svg-to-ts.ts'"
    }
  },
````

when I commit `import-conductor` is reordering the content of the `svg-to-ts.ts` file.

**Comment by shaharkazaz** [comment]
@kreuzerk if it's just this file, why not add the ignore comment (`// import-conductor-skip`)? seems cleaner as well.

**Comment by kreuzerk** [comment]
Using the comment works

**Comment by shaharkazaz** [comment]
@kreuzerk I've tested this use case as I showed you, I think it might be a problem with the path you specified.

**Pull request merged**
