### PR TITLE
Update file-helpers.ts

### PR DESCRIPTION
**Pull request by nmastereal**
fix: add missing space in comment inserted in svg to ts output

### CODE REVIEW

**Comment by nmastereal** [comment]
1. Created this entirely in the github UI because it was trivial. 
2. This was something that bothered me and our lint would flag upon generation. In our case prettier fixed it on our precommit but locally some devs get concerned.

**Review by kreuzerk — APPROVED** [review]
@nmastereal thx a lot for this PR. 👍

**Comment by kreuzerk** [comment]
@all-contributors please add @nmastereal for code

**Comment by nmastereal** [comment]
> @nmastereal thx a lot for this PR. 👍

Don't thank me so much for this! Its my smallest commit ever. Thanks maintainers for creating the project. 

How does your patch process work? Just curious when this eventually gets released or triggered to be released.

**Comment by kreuzerk** [comment]
@nmastereal the whole pipeline is full automated and uses semantic-release to automatically release a new version. But based on your commit message semantic release thought that no release was required so I made a dummy commit that releases your fix. As you can see v7.1.1 was successfully released today.

**Pull request merged**
