### PR TITLE
fix: 🐛 ensures name subset helper always has a unique name

### LINKED ISSUE #91: `IconNameSubset` duplicate name issue when using multiple icon sets
Hi, I believe we may have uncovered a potential breaking change while making a [switch from 5.0.1 to 5.7.1](https://github.com/Legal-and-General/canopy/pull/66), or alternatively it may be a misuse from our side.

In our project we have two sets of icons, [`icons`](https://legal-and-general-canopy.netlify.app/?path=/story/components-icon--standard) and [`brand-icons`](https://legal-and-general-canopy.netlify.app/?path=/story/components-brand-icon--standard). We isolate the two by running different svg-to-ts commands and generating separate files. 

[this change](https://github.com/kreuzerk/svg-to-ts/commit/d56e890f03fa5c96d2a19c918e19d7c2211a7b3e#diff-81a1c639d597a176fdd5574d01ddf126314b31a1e6eb072c66ad35ae181abb2bR92) in v5.6.0 which introduced the `IconNameSubset` causes us a bit of an issue is we now have two exported types with the same name.

```sh
An unhandled exception occurred: projects/canopy/src/public-api.ts:25:1 - error TS2308: Module './lib/icon/index' has already exported a member named 'IconNameSubset'. Consider explicitly re-exporting to resolve the ambiguity.
```

There are probably a few things we could to fix it in our project, but I thought I would raise it here first to see if you think it had any validity as a bug. If so I'm happy to raise a PR to try and fix it.

One route would be to provide some kind of cli option to prefix the type in the same way it's done for the [interface name](https://github.com/kreuzerk/svg-to-ts/blob/5635678fe2182ca9e8b7b59277295cf024fd87ee/src/lib/generators/code-snippet-generators.ts#L18). With a new option a breaking change could be avoided by deferring back to the default if no option is provided, the downside is that it might be a bit of an obscure option.

### PR DESCRIPTION
**Pull request by thatguynamedandy**
BREAKING CHANGE: The `IconNameSubset` helper is now dynamically generated based off of the `interfaceName` property. Any references to this will need updating.

fix #91

### CODE REVIEW

**Review by kreuzerk — APPROVED** [review]

**Comment by kreuzerk** [comment]
@thatguynamedandy - Sorry - I added you with the help of the all contributors as a contributor. I guess therefore you will now have conflicts in the `README.md`. I merged the other PR first because I wanted to ensure that you are listed as contributor if we release the new feature.

Could you resolve the conflicts? I could do it but it's on your fork so I think its easier if you could do it. Sorry for the circumstances.

**Comment by thatguynamedandy** [comment]
No worries all resolved.

The additional white space in the Readme seems to get added by the commit hook, hope thats ok.
I haven't used all-contributors before, looks great!

**Comment by kreuzerk** [comment]
@thatguynamedandy Thx a lot. FYI I changed the base branch to `release_v6` because I want to take this opportunity of introducing a breaking change to deliver another breaking change with it. I want to have a silent mode by default and a `verbose` flag to print more details to the log.

**Comment by thatguynamedandy** [comment]
@kreuzerk no worries makes perfect sense, thanks for the quick turnaround 👍

**Pull request merged**
