### PR TITLE
Commit formatting

### PR DESCRIPTION
**Pull request by thatguynamedandy**
Hi @kreuzerk. I found myself with a bit of capacity and hope you don't mind me suggesting a few potential improvements? Mostly around the structure and tooling of the repo as opposed to the actual library code, absolutely no pressure to merge if you aren't sure.

The work in this PR was concerned with tightening up the commit formatting. I've added...
- [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) configuration to the existing commitizen setup, this provides a cli step through of the formatting for people who want to use it. 
- [commitlint](https://www.npmjs.com/package/commitlint) to husky just to make sure the commit message is followed.
- the start of a Contribution doc which mostly outlines the above

Apologies for just jumping on in there, I can raise issues if you would prefer but it almost seemed quicker to raise the PR. 😁

### CODE REVIEW

**Comment by kreuzerk** [comment]
🤩  Wow. This is fantastic. I had this on my TODO list but didn't have the time to do it yet. 😉
Thank you very much. 👍

**Review by kreuzerk — APPROVED** [review]

**Comment by thatguynamedandy** [comment]
@kreuzerk no worries happy to help, if you fancy putting that TODO list somewhere I may be able to pick up the odd task. I was contemplating getting ESLint configured, with the end goal of maybe writing a test that lints the generated files to safeguard against any potential errors.

**Comment by kreuzerk** [comment]
@thatguynamedandy that sounds very nice. Yes, my TODO list currently is the following:

````
- Improve logging (in progress)
- Angular builder (basically finished - just some Docs missing)
- Commitlint, Contributions guidelines (what you did 👍 )
- Generation of helper code to build SVG element.
````
It's not so big since most things were done during Hacktoberfest.

I will try to create issues for improvements in the future. Also if you have an idea of how to enhance the project feel free to raise an issue or a PR.

**Pull request merged**
